version: "3"

networks:
  web:
    external: true

services:
  kaiware-api:
    image: $DOCKER_IMAGE
    environment:
      APP_NAME: $APP_NAME
      SERVER_PORT: $SERVER_PORT
      LOGGER_ENABLED: $LOGGER_ENABLED
      LOGGER_LEVEL: $LOGGER_LEVEL
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_DATABASE: $DB_DATABASE
      AUTH0_DOMAIN: $AUTH0_DOMAIN
      AUTH0_AUDIENCE: $AUTH0_AUDIENCE
    labels:
      - traefik.http.routers.kaiware-api.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.kaiware-api.tls=true
      - traefik.http.routers.kaiware-api.tls.certresolver=lets-encrypt
      - traefik.port=80
      - traefik.http.services.kaiware-api.loadbalancer.server.port=${SERVER_PORT}
    networks:
      - web